version: 2
updates:
  # Client Angular dependencies
  - package-ecosystem: 'npm'
    directory: '/client-angular'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    groups:
      angular-dependencies:
        patterns:
          - '@angular*'
    commit-message:
      prefix: 'deps(client)'
      include: 'scope'

  # Server dependencies
  - package-ecosystem: 'npm'
    directory: '/server'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'deps(server)'
      include: 'scope'

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'ci'
      include: 'scope'
