name: 'Setup Node.js and Install Dependencies'
description: 'Sets up Node.js and installs dependencies with robust error handling for lockfile mismatches and monorepo support.'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '22.x'
  cache-strategy:
    description: 'Caching strategy to use (npm, yarn, pnpm)'
    required: false
    default: 'npm'
  safe-install:
    description: 'Use npm install instead of npm ci for safer dependency resolution'
    required: false
    default: 'false'
  update-lockfile:
    description: 'Update the lockfile if dependencies are mismatched'
    required: false
    default: 'false'
  check-missing:
    description: 'Check for and attempt to install missing dependencies'
    required: false
    default: 'false'
  working-directory:
    description: 'Directory to run npm commands in'
    required: false
    default: '.'

outputs:
  lockfile-valid:
    description: 'Whether the lockfile is valid JSON'
    value: ${{ env.LOCKFILE_VALID }}

runs:
  using: 'composite'
  steps:
    - name: Ensure jq is installed
      shell: bash
      run: |
        if ! command -v jq >/dev/null 2>&1; then
          echo "jq is required but not installed!"
          exit 1
        fi

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache-strategy }}

    - name: Move to project directory
      shell: bash
      run: cd "${{ inputs.working-directory }}"
      working-directory: ${{ inputs.working-directory }}

    - name: Check npm and node version
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "Using npm version: $(npm --version)"
        echo "Using node version: $(node --version)"

    - name: Verify package.json and lockfile
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        if [ -f package.json ]; then
          echo "Found package.json"
          if [ -f package-lock.json ]; then
            echo "Found package-lock.json"
            if ! jq empty package-lock.json 2>/dev/null; then
              echo "Warning: package-lock.json is not valid JSON. Will use npm install instead of npm ci."
              echo "LOCKFILE_VALID=false" >> $GITHUB_ENV
            else
              echo "Lockfile is valid JSON"
              echo "LOCKFILE_VALID=true" >> $GITHUB_ENV
            fi
          else
            echo "No package-lock.json found. Will use npm install."
            echo "LOCKFILE_VALID=false" >> $GITHUB_ENV
          fi
        else
          echo "Error: package.json not found!"
          exit 1
        fi

    - name: Install dependencies (safe mode)
      if: ${{ inputs.safe-install == 'true' || env.LOCKFILE_VALID != 'true' }}
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        echo "Using npm install for safe dependency resolution..."
        if [ "${{ inputs.update-lockfile }}" = "true" ]; then
          npm install --no-audit --package-lock-only || npm install --package-lock-only
        else
          npm install --no-audit || npm install
        fi

    - name: Install dependencies (strict mode)
      if: ${{ inputs.safe-install != 'true' && env.LOCKFILE_VALID == 'true' }}
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        echo "Using npm ci for clean installation..."
        npm ci || {
          echo "npm ci failed, falling back to npm install..."
          npm install
          if [ "${{ inputs.update-lockfile }}" = "true" ]; then
            npm install
          fi
        }

    - name: Check for missing dependencies
      if: ${{ inputs.check-missing == 'true' }}
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        echo "Checking for missing dependencies..."
        DEPS=$(jq -r '.dependencies, .devDependencies | to_entries[] | .key' package.json 2>/dev/null)
        MISSING=""
        for DEP in $DEPS; do
          if ! npm list $DEP --depth=0 --silent 2>/dev/null; then
            MISSING="$MISSING $DEP"
          fi
        done
        if [ -n "$MISSING" ]; then
          echo "Warning: The following dependencies might be missing:$MISSING"
          for DEP in $MISSING; do
            npm install $DEP || echo "Failed to install $DEP"
          done
        else
          echo "All dependencies appear to be installed."
        fi