import { NgModule } from '@angular/core';
import {
  NbThemeModule,
  NbLayoutModule,
  NbCardModule,
  NbButtonModule,
  NbIconModule,
  NbBadgeModule,
  NbTagModule,
  NbDialogModule,
  NbToastrModule,
  NbMenuModule,
  NbSidebarModule,
  NbTabsetModule,
  NbInputModule,
  NbSelectModule,
  NbCheckboxModule,
  NbRadioModule,
  NbDatepickerModule,
  NbTimepickerModule,
  NbFormFieldModule,
  NbAutocompleteModule,
  NbUserModule,
  NbActionsModule,
  NbSearchModule,
  NbListModule,
  NbProgressBarModule,
  NbSpinnerModule,
  NbContextMenuModule,
  NbPopoverModule,
  NbTooltipModule,
  NbWindowModule,
  NbChatModule,
  NbAlertModule,
  NbAccordionModule,
  NbStepperModule,
  NbTreeGridModule,
} from '@nebular/theme';
import { NbEvaIconsModule } from '@nebular/eva-icons';

const NEBULAR_MODULES = [
  NbThemeModule,
  NbLayoutModule,
  NbCardModule,
  NbButtonModule,
  NbIconModule,
  NbBadgeModule,
  NbTagModule,
  NbDialogModule,
  NbToastrModule,
  NbMenuModule,
  NbSidebarModule,
  NbTabsetModule,
  NbInputModule,
  NbSelectModule,
  NbCheckboxModule,
  NbRadioModule,
  NbDatepickerModule,
  NbTimepickerModule,
  NbFormFieldModule,
  NbAutocompleteModule,
  NbUserModule,
  NbActionsModule,
  NbSearchModule,
  NbListModule,
  NbProgressBarModule,
  NbSpinnerModule,
  NbContextMenuModule,
  NbPopoverModule,
  NbTooltipModule,
  NbWindowModule,
  NbChatModule,
  NbAlertModule,
  NbAccordionModule,
  NbStepperModule,
  NbTreeGridModule,
  NbEvaIconsModule,
];

@NgModule({
  imports: [
    NbThemeModule.forRoot({ name: 'default' }),
    NbDialogModule.forRoot(),
    NbToastrModule.forRoot(),
    NbMenuModule.forRoot(),
    NbSidebarModule.forRoot(),
    NbDatepickerModule.forRoot(),
    NbTimepickerModule.forRoot(),
    NbWindowModule.forRoot(),
    ...NEBULAR_MODULES,
  ],
  exports: [...NEBULAR_MODULES],
})
export class NebularModule {}
