name: Angular Tests

on:
  push:
    branches: [main, develop]
    paths:
      - 'client-angular/**'
      - '.github/workflows/angular-tests.yml' # Trigger on workflow changes too
  pull_request:
    branches: [main, develop]
    paths:
      - 'client-angular/**'
      - '.github/workflows/angular-tests.yml' # Trigger on workflow changes too

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
    timeout-minutes: 20

    strategy:
      matrix:
        node-version: [20.x, 18.x] # Stable Node.js versions

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          cd ./client-angular
          npm ci # Clean install dependencies
          # Install Angular CLI globally if needed
          npm install -g @angular/cli

      # Step 4: Run Unit Tests
      # Ensure ChromeHeadless is installed for tests
      - name: Install Chrome Browser
        run: sudo apt-get install -y google-chrome-stable

      - name: Run Unit Tests
        working-directory: ./client-angular
        run: npm test -- --watch=false --browsers=ChromeHeadless --no-progress

      # Step 5: Prepare test results directory
      - name: Prepare Test Results Directory
        run: |
          mkdir -p downloaded-reports/angular
          cp -r ./client-angular/coverage/* downloaded-reports/angular/ || true

      # Step 6: Upload test results as an artifact
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            ./client-angular/coverage
            downloaded-reports/angular
          if-no-files-found: warn

  e2e:
    runs-on: ubuntu-latest
    env:
      CI: true
    timeout-minutes: 30

    strategy:
      matrix:
        node-version: [20.x, 18.x]

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          cd ./client-angular
          npm ci # Clean install dependencies
          # Install Angular CLI globally if needed
          npm install -g @angular/cli

      # Step 4: Start Angular App
      # Use `npx ng serve` to start the app
      - name: Start Angular App
        working-directory: ./client-angular
        run: npx ng serve --host=0.0.0.0 --port=4200 &
        env:
          CI: true

      # Step 5: Wait for the app to be ready
      - name: Wait for App
        run: npx wait-on http://localhost:4200

      # Step 6: Run Cypress Tests
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./client-angular
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:4200'
          browser: chrome

      # Step 7: Prepare Cypress screenshots directory
      - name: Prepare Cypress Screenshots Directory
        if: failure()
        run: |
          mkdir -p downloaded-reports/angular/cypress-screenshots
          cp -r ./client-angular/cypress/screenshots/* downloaded-reports/angular/cypress-screenshots/ || true

      # Step 8: Upload Cypress screenshots as an artifact
      - name: Upload Cypress Screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: |
            ./client-angular/cypress/screenshots
            downloaded-reports/angular/cypress-screenshots
          if-no-files-found: warn

  lint:
    runs-on: ubuntu-latest
    env:
      CI: true
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [20.x, 18.x]

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Install ESLint and Angular ESLint plugins
      - name: Install ESLint
        run: |
          cd ./client-angular
          npm install eslint @angular-eslint/builder @angular-eslint/eslint-plugin @angular-eslint/eslint-plugin-template --save-dev

      # Step 4: Run ESLint
      - name: Run ESLint
        working-directory: ./client-angular
        run: npx ng lint client-angular
