name: Angular Client Lint

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'client-angular/**'
      - '.github/workflows/angular-client-lint.yml'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'client-angular/**'
  workflow_dispatch:
    inputs:
      node-version:
        description: 'Specify Node.js version'
        required: false
        default: '22.14.0'

jobs:
  lint-angular-client:
    runs-on: ubuntu-latest
    name: Lint Angular Client (Node ${{ matrix.node-version }})
    defaults:
      run:
        working-directory: ./client-angular

    strategy:
      matrix:
        node-version: ['22.14.0']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Node.js Version
        run: node --version

      - name: Setup Node.js with Caching
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: |
            client-angular/package-lock.json
            client-angular/yarn.lock

      - name: Debug Directory Structure
        run: ls -la client-angular

      - name: Check for Cache Paths
        run: |
          if [ ! -f client-angular/package-lock.json ]; then
            echo "Warning: package-lock.json not found. Skipping cache."
            exit 0
          fi

      - name: Install Dependencies
        run: npm ci

      - name: Check for ESLint Configuration
        run: |
          if [ ! -f .eslintrc.json ]; then
            echo "ESLint configuration not found, running ng add."
            npx ng add @angular-eslint/schematics --skip-confirmation
          else
            echo "ESLint configuration found, skipping ng add."
          fi

      - name: Run ESLint
        run: npx ng lint client-angular