name: Angular Tests

on:
  push:
    branches: [main, develop, Nebular-UI-Refactor]
    paths:
      - 'client-angular/**'  # Trigger workflow for changes in Angular client
      - '.github/workflows/angular-tests.yml'  # Trigger workflow changes
  pull_request:
    branches: [main, develop]
    paths:
      - 'client-angular/**'
      - '.github/workflows/angular-tests.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
    timeout-minutes: 20

    strategy:
      matrix:
        node-version: [20.x, 18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          cd ./client-angular
          npm ci
          npm install yargs --save-dev

      - name: Setup Chrome Browser
        uses: browser-actions/setup-chrome@v1

      - name: Run Unit Tests
        working-directory: ./client-angular
        run: npm test -- --watch=false --browsers=ChromeHeadless --no-progress || echo "Tests failed"

      - name: Prepare Test Results Directory
        run: |
          mkdir -p downloaded-reports/angular
          cp -r ./client-angular/coverage/* downloaded-reports/angular/ || true

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            ./client-angular/coverage
            downloaded-reports/angular
          if-no-files-found: ignore

  e2e:
    runs-on: ubuntu-latest
    env:
      CI: true
    timeout-minutes: 30

    strategy:
      matrix:
        node-version: [20.x, 18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start Angular App
        run: npm start -- --host=0.0.0.0 --port=4200

      - name: Verify App is Running
        run: curl -I http://localhost:4200

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./client-angular
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:4200'
          browser: chrome

      - name: Prepare Cypress Screenshots Directory
        if: failure()
        run: |
          mkdir -p downloaded-reports/angular/cypress-screenshots
          cp -r ./client-angular/cypress/screenshots/* downloaded-reports/angular/cypress-screenshots/ || true

      - name: Upload Cypress Screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: |
            ./client-angular/cypress/screenshots
            downloaded-reports/angular/cypress-screenshots
          if-no-files-found: warn

  lint:
    runs-on: ubuntu-latest
    env:
      CI: true
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [20.x, 18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies for Linting
        run: |
          cd ./client-angular
          npm ci

      - name: Run ESLint
        working-directory: ./client-angular
        run: npx ng lint client-angular