# .github/workflows/base-config.yml
# Add this shared configuration file for reusable properties
name: Base Configuration

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version'
        required: false
        type: string
        default: '22.x'

env:
  REPORTS_DIR: downloaded-reports
  ARTIFACTS_DIR: .github/artifacts
  REPORTS_SECURITY: downloaded-reports/security
  REPORTS_TESTING: downloaded-reports/testing
  REPORTS_DOCS: downloaded-reports/docs
  REPORTS_ANGULAR: downloaded-reports/angular
  REPORTS_SERVER: downloaded-reports/server
  REPORTS_SNYK: downloaded-reports/snyk
  RETENTION_ARTIFACTS: 14

jobs:
  node-setup:
    name: Setup Node.js Environment
    runs-on: ubuntu-latest
    outputs:
      node-path: ${{ steps.get-node-path.outputs.node-path }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        id: node-setup
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
      - name: Get Node.js path
        id: get-node-path
        run: echo "node-path=$(which node)" >> $GITHUB_OUTPUT

  mongodb-setup:
    name: Setup MongoDB Service
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017

  setup-reports:
    name: Setup Report Directories
    runs-on: ubuntu-latest
    steps:
      - name: Create report directories
        run: |
          mkdir -p \
            ${{ env.REPORTS_SECURITY }} \
            ${{ env.REPORTS_TESTING }} \
            ${{ env.REPORTS_DOCS }} \
            ${{ env.REPORTS_ANGULAR }} \
            ${{ env.REPORTS_SERVER }} \
            ${{ env.REPORTS_SNYK }}

      - name: Configure artifact retention
        run: |
          echo "Uploading reports to artifacts"

          if [ -d "${{ env.REPORTS_DIR }}" ]; then
            echo "Reports directory exists, proceeding with upload"
            
            # Upload the reports directory as an artifact
            tar -czvf reports.tar.gz "${{ env.REPORTS_DIR }}"
            
            echo "Reports directory compressed successfully"
            
            mv reports.tar.gz "${{ env.ARTIFACTS_DIR }}"
            
            echo "Reports directory moved to artifacts directory"
            
            echo "Uploading artifact"
            
            # Upload the reports artifact
            curl -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -H "Content-Type: application/json" \
              -d '{
                "name": "reports",
                "path": "${{ env.ARTIFACTS_DIR }}/reports.tar.gz",
                "retention_days": ${{ env.RETENTION_ARTIFACTS }}
              }' \
              "https://api.github.com/repos/${{ github.repository }}/actions/artifacts"
          else
            echo "Reports directory does not exist, skipping upload"
          fi
