name: Base Configuration

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: false
        type: string
        default: '20.x'
      package-manager:
        description: 'Package manager to use (npm or pnpm)'
        required: false
        type: string
        default: 'pnpm'

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

env:
  CI: true
  REPORTS_DIR: reports
  ARTIFACTS_RETENTION: 14

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: ./.github/actions/setup-nodejs
        with:
          node-version: ${{ inputs.node-version }}
          
      - name: Verify Dependencies
        id: deps
        run: |
          if [ -f "pnpm-lock.yaml" ]; then
            npm install -g pnpm
            pnpm install --frozen-lockfile
          else
            npm ci
          fi
        continue-on-error: true
          
      - name: Fallback Install
        if: steps.deps.outcome == 'failure'
        run: |
          echo "Clean install failed, attempting regular install..."
          rm -rf node_modules
          npm install
          
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json', '**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-