name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read       # For checking out code
  checks: write       # For creating check runs
  pull-requests: write # For commenting on PRs
  statuses: write    # For setting commit status

jobs:
  lint-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js and dependencies
        uses: ./.github/actions/setup-nodejs
        with:
          working-directory: client
          node-version: 22.x
          safe-install: 'true'
          check-missing: 'true'
      - name: Run lint
        working-directory: client
        run: npm run lint

  lint-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js and dependencies
        uses: ./.github/actions/setup-nodejs
        with:
          working-directory: server
          node-version: 22.x
          safe-install: 'true'
          check-missing: 'true'
      - name: Run lint
        working-directory: server
        run: npm run lint

  # ...repeat for other subprojects and jobs as needed

  test-root:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js and dependencies
        uses: ./.github/actions/setup-nodejs
        with:
          working-directory: .
          node-version: 22.x
          safe-install: 'false'
          check-missing: 'true'
      - name: Run tests
        run: npm test