name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-nodejs
        with:
          node-version: ${{ matrix.node-version }}

      - name: Lint code
        run: npm run lint

      - name: Run server tests
        run: npm run test:server

      - name: Run client tests
        run: npm run test:client

  security-audit:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-nodejs
        with:
          node-version: 22.x

      - name: Run security audit
        run: npm run analyze:security

      - name: Upload audit report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: npm-audit-report
          path: npm-audit.json
