name: Cleanup Artifacts

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env:
      REPORTS_BASE_DIR: downloaded-reports
    steps:
      - name: Cleanup old reports
        run: |
          find ${{ env.REPORTS_BASE_DIR }} -type f -mtime +30 -delete
          find ${{ env.REPORTS_BASE_DIR }} -type d -empty -delete