name: Documentation Generation and Deployment

# This workflow is deprecated. All documentation generation and deployment is now handled by generate-docs.yml.
# Please update any references to use generate-docs.yml instead.

on:
  push:
    branches: [main]
    paths:
      - 'client-angular/src/**/*.ts'
      - 'client-angular/src/**/*.js'
      - 'server/**/*.js'
      - 'docs/**/*.md'
      - '_docs_index.html'
      - '_glossary.html'
      - '**/*.html'
      - 'scripts/generate_docs.js'
      - '.github/workflows/docs-generation-and-deployment.yml'
  pull_request:
    branches: [main]
    paths:
      - 'client-angular/src/**/*.ts'
      - 'client-angular/src/**/*.js'
      - 'server/**/*.js'
      - 'docs/**/*.md'
      - 'scripts/generate_docs.js'
      - '.github/workflows/docs-generation-and-deployment.yml'
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-nodejs
        with:
          node-version: '22'

      - name: Install marked
        run: npm install marked

      - name: Create documentation directories
        run: |
          mkdir -p downloaded-reports/docs

      - name: Generate documentation
        run: node scripts/generate_docs.js --verbose --migrate-docs --output-dir=downloaded-reports/docs

      - name: Commit changes
        if: github.event_name != 'pull_request'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Update documentation [skip ci]"
          git push

  deploy-to-pages:
    needs: generate-docs
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main # Ensure we have the latest changes after documentation generation

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'downloaded-reports/docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
