name: Documentation
on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v4

      - name: Build documentation
        run: |
          cd docs
          npm ci
          npm run build

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation-${{ github.run_id }}
          path: docs/build
          retention-days: 14

  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-nodejs
        with:
          node-version: '22'
