name: Frogbot Security Scan

on:
  pull_request:
    branches: [ main ] # Change if your default branch is different
  workflow_dispatch:

jobs:
  frogbot-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Run Frogbot
      - name: Run Frogbot scan
        uses: jfrog/frogbot@v2
        # Frogbot now expects your JFrog credentials as environment variables
        env:
          JF_URL: ${{ secrets.JF_URL }}             # Full JFrog Platform URL (e.g. https://mycompany.jfrog.io/)
          JF_USER: ${{ secrets.JF_USER }}           # Your JFrog username/email
          #JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}   # Or use JF_ACCESS_TOKEN below
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }} # Use instead of password if you prefer
