name: Generate Documentation

on:
  push:
    branches: [main]
    paths:
      - '**/*.js'
      - '**/*.ts'
      - '**/*.html'
      - 'docs/**/*.md'
      - '_docs_index.html'
      - '_glossary.html'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-nodejs
        with:
          node-version: '22'
      - name: Ensure each folder has required HTML docs
        run: node scripts/generate_docs.js --verbose
      - name: Parse source code to update glossaries
        run: node scripts/generate_docs.js --update-only --verbose
      - name: Rebuild documentation indexes
        run: node scripts/generate_docs.js --migrate-docs --verbose
      - name: Commit changes
        if: github.event_name != 'pull_request'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "**/*.html"
          git diff --quiet && git diff --staged --quiet || git commit -m "Update documentation [skip ci]"
          git push
