name: Generate Documentation

on:
  push:
    branches: [main]
    paths:
      - '**/*.js'
      - '**/*.ts'
      - '**/*.html'
      - 'docs/**/*.md'
      - '_docs_index.html'
      - '_glossary.html'
      - 'scripts/generate_docs.js'
      - '.github/workflows/generate-docs.yml'
  pull_request:
    branches: [main]
    paths:
      - '**/*.js'
      - '**/*.ts'
      - '**/*.html'
      - 'docs/**/*.md'
      - 'scripts/generate_docs.js'
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 30 # Add timeout to prevent runaway jobs
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for proper documentation generation
      
      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-nodejs
        with:
          node-version: '22'
          safe-install: 'true'
          update-lockfile: 'false'
          check-missing: 'true'
      
      - name: Install marked package for Markdown processing
        run: npm install marked
      
      - name: Create documentation directories
        run: |
          mkdir -p downloaded-reports/docs
      
      # Step 1: Ensure each folder has required HTML docs
      - name: Ensure each folder has required HTML docs
        run: node scripts/generate_docs.js --verbose
      
      # Step 2: Parse source code to update glossaries
      - name: Parse source code to update glossaries
        run: node scripts/generate_docs.js --update-only --verbose
      
      # Step 3: Rebuild documentation indexes and migrate Markdown to HTML
      - name: Rebuild documentation indexes
        run: node scripts/generate_docs.js --migrate-docs --verbose
      
      # Step 4: Generate documentation for GitHub Pages
      - name: Generate documentation for GitHub Pages
        run: node scripts/generate_docs.js --verbose --migrate-docs --output-dir=downloaded-reports/docs
      
      # Step 5: Commit changes (only HTML files)
      - name: Commit changes
        if: github.event_name != 'pull_request'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "**/*.html"
          git diff --quiet && git diff --staged --quiet || git commit -m "Update documentation [skip ci]"
          git push
      
      # Upload documentation as artifact
      - name: Upload documentation as artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: downloaded-reports/docs
          retention-days: 14
          if-no-files-found: warn

  deploy-to-pages:
    needs: generate-docs
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Download documentation artifact
        uses: actions/download-artifact@v4
        with:
          name: documentation
          path: docs-to-deploy
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'docs-to-deploy'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
