name: "JFrog Integration Example"
on: push

permissions:
  contents: write    # For publishing artifacts
  actions: read     # For reading build status
  pull-requests: write # For commenting results

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Setup Node npm
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Install Client Dependencies
        run: cd client-angular && npm ci

      - name: Set CLI Config
        run: jf npm-config --global=true --repo-resolve=ht-npm --repo-deploy=ht-npm || echo "JFrog CLI config failed - credentials may be missing"

      - name: Install Deps with JFrog
        run: jf npm install || echo "JFrog npm install failed - using regular npm install"

      - name: Run tests
        run: npm test

      - name: Publish
        run: jf npm publish || echo "JFrog publish failed - credentials may be missing"

      - name: Publish Build info With JFrog CLI
        run: |
          # Collect environment variables for the build
          jf rt build-collect-env || echo "Failed to collect build env"
          # Collect VCS details from git and add them to the build
          jf rt build-add-git || echo "Failed to add git info"
          # Publish build info
          jf rt build-publish || echo "Failed to publish build info - credentials may be missing"
