name: Monitoring

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_run:
    workflows: 
      - 'Tests'
      - 'Angular Tests'
      - 'Server Tests'
    types: 
      - completed
    branches:
      - '**'  # Updated to match any branch
  workflow_dispatch:

permissions:
  actions: read       # For reading workflow runs
  contents: read      # For reading repository content
  issues: write      # For creating monitoring issues
  pull-requests: read # For checking PR status

# Prevent multiple instances from running concurrently
concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch || github.ref }}
  cancel-in-progress: true

jobs:
  collect-insights:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Reports
        run: node .github/scripts/generate-reports.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ github.run_id }}
          path: |
            ./reports/workflow-errors/
            ./reports/insights/
            ./reports/test-results/
          retention-days: 14

  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-nodejs
        with:
          node-version: '22'
