name: Server Tests

on:
  push:
    branches: [main, develop]
    paths:
      - 'server/**'
      - '.github/workflows/server-tests.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'server/**'

# Add concurrency settings to cancel in-progress runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-nodejs
        with:
          node-version: '22.x'
        working-directory: server

      - name: Run tests
        run: npm test
        working-directory: server
        env:
          NODE_ENV: test
          MONGODB_URI: mongodb://localhost:27017/test

  lint:
    runs-on: ubuntu-latest
    env:
      CI: true
    timeout-minutes: 10 # Add timeout to prevent runaway jobs

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-nodejs
        with:
          node-version: ${{ matrix.node-version }}
        working-directory: ./server

      - name: Run ESLint
        working-directory: ./server
        run: npx eslint .
        # continue-on-error: true # <-- REMOVED: Lint errors will now fail the workflow
