name: Server Tests

on:
  push:
    branches: [main, develop]
    paths:
      - 'server/**'
      - '.github/workflows/server-tests.yml' # Trigger on workflow changes too
  pull_request:
    branches: [main, develop]
    paths:
      - 'server/**'
      - '.github/workflows/server-tests.yml' # Trigger on workflow changes too

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
    timeout-minutes: 20 # Add timeout to prevent runaway jobs

    strategy:
      matrix:
        node-version: [22.x]

    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          # Removed caching configuration since package-lock.json doesn't exist

      - name: Install dependencies
        working-directory: ./server
        run: npm install

      - name: Run unit tests
        working-directory: ./server
        run: npm test
        env:
          NODE_ENV: test
          MONGODB_URI: mongodb://localhost:27017/date-night-test

      - name: Run integration tests
        working-directory: ./server
        run: npm run test:integration
        env:
          NODE_ENV: test
          MONGODB_URI: mongodb://localhost:27017/date-night-test

      - name: Prepare test results directory
        run: |
          mkdir -p downloaded-reports/server
          cp -r ./server/coverage/* downloaded-reports/server/ || true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: server-test-results
          path: |
            ./server/coverage
            downloaded-reports/server
          if-no-files-found: warn

  lint:
    runs-on: ubuntu-latest
    env:
      CI: true
    timeout-minutes: 10 # Add timeout to prevent runaway jobs

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          # Removed caching configuration since package-lock.json doesn't exist

      - name: Install dependencies
        working-directory: ./server
        run: npm install

      - name: Run ESLint
        working-directory: ./server
        run: npx eslint .
        # continue-on-error: true # <-- REMOVED: Lint errors will now fail the workflow
