name: Sync Workflow Error Logs

on:
  workflow_run:
    workflows: ['*']
    types:
      - completed
  schedule:
    - cron: '0 */6 * * *' # Run every 6 hours
  workflow_dispatch: # Allow manual triggering

jobs:
  sync-error-logs:
    runs-on: ubuntu-latest
    env:
      CI: true
    permissions:
      contents: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install @octokit/rest@19.0.13 fs-extra@11.2.0 adm-zip@0.5.10

      - name: Fetch workflow run logs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name || github.repository.name }}
        run: node scripts/fetch-workflow-logs.js

      - name: Create README for logs
        run: |
          cat > downloaded-reports/workflow-errors/README.md << 'EOF'
          # Workflow Error Logs

          This directory contains logs from failed GitHub Actions workflow runs. These logs are automatically collected by the "Sync Workflow Error Logs" workflow.

          ## Directory Structure

          ```
          workflow-errors/
          ├── {workflow-name}/
          │   ├── {date}_{run-id}/
          │   │   ├── metadata.json       # Run metadata
          │   │   ├── jobs.json           # Jobs metadata
          │   │   ├── {job-name}/
          │   │   │   ├── job-metadata.json  # Job metadata
          │   │   │   └── logs.txt           # Job logs (extracted from zip if necessary)
          │   │   │   └── [other extracted files] # Additional files from zip archives
          │   │   └── ...
          │   └── ...
          └── ...
          ```

          ## Using These Logs

          These logs can be used to diagnose and fix issues with GitHub Actions workflows. Look for error messages, failed steps, and other indicators of problems.

          ## Automatic Collection

          Logs are collected:
          - After any workflow completes
          - Every 6 hours via scheduled run
          - Manually via workflow dispatch

          ## Retention

          Only logs from the past 30 days are collected.

          ## Implementation Details

          The logs are fetched using the GitHub API and processed with the `adm-zip` library to extract text content from zip files when necessary. This ensures that all logs are stored in a readable text format.
          EOF

      - name: Commit and push logs
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Handle any unstaged changes by stashing them
          git stash -u || true

          # Pull the latest changes with rebase strategy to avoid merge commits
          git pull --rebase origin main

          # Pop the stash if we stashed anything
          git stash list | grep -q "stash@{0}" && git stash pop || true

          # Add only the workflow-errors directory
          git add downloaded-reports/workflow-errors

          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update workflow error logs [skip ci]"
            git push
          fi
