name: Sync Snyk Issues

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight
  workflow_dispatch: # Allow manual triggering

jobs:
  sync-snyk-issues:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          npm install
          cd server && npm install
          cd ../client-angular && npm install
          # Install Snyk as a dev dependency instead of globally
          npm install --save-dev snyk

      - name: Authenticate with Snyk
        run: npx snyk auth ${{ secrets.SNYK_TOKEN }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Standard vulnerability tests for individual projects
      - name: Scan root project
        run: npx snyk test --json > snyk-root-results.json || true

      - name: Scan server project
        run: cd server && npx snyk test --json > ../snyk-server-results.json || true

      - name: Scan client project
        run: cd client-angular && npx snyk test --json > ../snyk-client-results.json || true

      # Generate optimized dependency trees (with depth limit to reduce file size)
      - name: Generate dependency tree for root
        run: npm ls --json --depth=2 > npm-root-deps-tree.json || true

      - name: Generate dependency tree for server
        run: cd server && npm ls --json --depth=2 > ../npm-server-deps-tree.json || true

      - name: Generate dependency tree for client
        run: cd client-angular && npm ls --json --depth=2 > ../npm-client-deps-tree.json || true

      # Get upgrade recommendations
      - name: Get upgrade recommendations for root
        run: npx snyk test --json --dev --severity-threshold=low --print-deps > snyk-root-upgrade-paths.json || true

      - name: Get upgrade recommendations for server
        run: cd server && npx snyk test --json --dev --severity-threshold=low --print-deps > ../snyk-server-upgrade-paths.json || true

      - name: Get upgrade recommendations for client
        run: cd client-angular && npx snyk test --json --dev --severity-threshold=low --print-deps > ../snyk-client-upgrade-paths.json || true

      # Generate reports
      - name: Generate prioritized task list
        run: |
          mkdir -p downloaded-reports/snyk
          node .github/scripts/generate-snyk-task-list.js

      # Clean up large JSON files to avoid bloating the repository
      - name: Clean up large JSON files
        run: |
          # Keep only the most recent JSON files
          find . -name "npm-*-deps-tree.json" -type f -size +1M -delete || true
          # Compress remaining large files
          find . -name "*.json" -type f -size +1M -exec gzip -9 {} \; || true

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit and push changes
        run: |
          git add downloaded-reports/snyk/
          git commit -m "docs: update Snyk issues task list [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
