name: Sync Snyk Issues

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight
  workflow_dispatch: # Allow manual triggering

jobs:
  sync-snyk-issues:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Install dependencies
        run: |
          npm install
          cd server && npm install
          cd ../client-angular && npm install

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Standard vulnerability tests
      - name: Scan root project
        run: snyk test --json > snyk-root-results.json || true

      - name: Scan server project
        run: cd server && snyk test --json > ../snyk-server-results.json || true

      - name: Scan client project
        run: cd client-angular && snyk test --json > ../snyk-client-results.json || true

      # Dependency vulnerability tests with detailed output
      - name: Scan root project dependencies
        run: snyk test --all-projects --json > snyk-root-deps-results.json || true

      - name: Generate dependency tree for root
        run: npm ls --json > npm-root-deps-tree.json || true

      - name: Generate dependency tree for server
        run: cd server && npm ls --json > ../npm-server-deps-tree.json || true

      - name: Generate dependency tree for client
        run: cd client-angular && npm ls --json > ../npm-client-deps-tree.json || true

      # Get upgrade recommendations
      - name: Get upgrade recommendations for root
        run: snyk test --json --dev --severity-threshold=low --print-deps > snyk-root-upgrade-paths.json || true

      - name: Get upgrade recommendations for server
        run: cd server && snyk test --json --dev --severity-threshold=low --print-deps > ../snyk-server-upgrade-paths.json || true

      - name: Get upgrade recommendations for client
        run: cd client-angular && snyk test --json --dev --severity-threshold=low --print-deps > ../snyk-client-upgrade-paths.json || true

      # Generate reports
      - name: Generate prioritized task list
        run: |
          mkdir -p docs/snyk-reports
          node .github/scripts/generate-snyk-task-list.js

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit and push changes
        run: |
          git add docs/snyk-reports/
          git commit -m "docs: update Snyk issues task list [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
