name: Sync Workflow Errors

on:
  workflow_run:
    workflows: ["*"]
    types: [completed]
    branches: [main, develop]
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual triggers

env:
  ARTIFACTS_RETENTION: 14

permissions:
  actions: read       # For reading workflow runs
  contents: write    # For committing error reports
  issues: write      # For creating error issues
  pull-requests: write # For commenting on PRs
  checks: write      # For creating check runs

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch || github.ref }}
  cancel-in-progress: true

jobs:
  sync-errors:
    if: contains(fromJSON('["failure", "cancelled", "timed_out"]'), github.event.workflow_run.conclusion)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      actions: read
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install Dependencies
        run: |
          npm ci
          npm install @octokit/rest@20 adm-zip@0.5.10
      
      - name: Disable Husky
        run: node .github/scripts/disable-husky-in-ci.js
      
      - name: Fetch Workflow Logs
        id: fetch-logs
        run: |
          mkdir -p workflow-error-logs-temp
          node .github/scripts/fetch-workflow-logs.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW_RUN_ID: ${{ github.event.workflow_run.id }}
          
      - name: Run Analyzer Tests
        run: |
          echo "Running error analyzer tests..."
          node .github/scripts/test-error-analyzer.js
          
      - name: Generate Error Report
        if: success()
        run: |
          echo "Generating error report..."
          node .github/scripts/analyze-workflow-errors.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Run Error Pattern Validation
        run: |
          echo "Validating error patterns against latest logs..."
          node .github/scripts/validate-error-patterns.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload Error Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: workflow-error-logs-${{ github.run_id }}
          path: |
            workflow-error-logs-temp/
            workflow-error-report.md
          retention-days: ${{ env.ARTIFACTS_RETENTION }}