name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  server-tests:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v4
      - name: Run Server Tests
        run: |
          cd server
          npm ci
          npm test
        env:
          NODE_ENV: test
          MONGODB_URI: mongodb://localhost:27017/test

  client-tests:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v4
      - name: Run Client Tests
        run: |
          cd client-angular
          npm ci
          npm test -- --no-watch --no-progress --browsers=ChromeHeadless

  setup:
    uses: ./.github/workflows/base-config.yml@main
    with:
      node-version: '18'
