name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  server-tests:
    name: Server Tests
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          cache: 'npm'
      - name: Install dependencies
        run: |
          cd server
          npm ci
      - name: Run server tests
        run: |
          cd server
          npm test
        env:
          NODE_ENV: test
          MONGODB_URI: mongodb://localhost:27017/test

  client-tests:
    name: Client Tests
    runs-on: ubuntu-latest
    needs: server-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          cache: 'npm'
      - name: Install dependencies
        run: |
          cd client-angular
          npm ci
      - name: Run client tests
        run: |
          cd client-angular
          npm test -- --no-watch --no-progress --browsers=ChromeHeadless
