name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  server-tests:
    name: Server Tests
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-nodejs
        with:
          node-version: '22.14.0'
      - name: Run server tests
        run: |
          npm test
        working-directory: server
        env:
          NODE_ENV: test

  client-tests:
    name: Client Tests
    runs-on: ubuntu-latest
    needs: server-tests
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-nodejs
        with:
          node-version: '22.14.0'
      - name: Run client tests
        run: |
          npm test -- --no-watch --no-progress --browsers=ChromeHeadless
        working-directory: client-angular
