name: Trivy Security Scan

on:
  push:
    branches:
      - "**" # Triggers on any branch where commits are pushed

permissions:
  contents: read
  security-events: write  # For uploading security scan results
  issues: write           # For creating security issues
  checks: write           # For creating check runs
  pull-requests: write    # For commenting on PRs

jobs:
  trivy-scan:
    name: Run Trivy Scan
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the branch where the commit was made
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          submodules: recursive

      # Step 2: Initialize Git Submodules (if any exist)
      - name: Initialize Submodules
        run: git submodule update --init --recursive

      # Step 3: Install Trivy (latest version from Aqua Security repository)
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      # Step 4: Scan the repository for vulnerabilities ONLY (disable secret scanning for faster results)
      - name: Trivy Scan for Vulnerabilities Only
        run: |
          # Only scan for vulnerabilities (no secret scanning), for faster scan times as recommended
          trivy fs --scanners vuln --exit-code 1 --severity HIGH,CRITICAL .

      # Step 5: Handle Trivy Warnings (Optional)
      - name: Handle Trivy Warnings (Optional)
        if: failure()
        run: echo "Review Trivy scan warnings for details."

      # Step 6: Scan dependencies for vulnerabilities ONLY (again, disables secret scanning for speed)
      - name: Scan Dependencies for Vulnerabilities Only
        run: |
          # Only scan for vulnerabilities again, e.g. in dependencies (if needed)
          trivy fs --scanners vuln --exit-code 1 .
